; PlatformIO Project Configuration File - Minimal Core Example
;
; This example demonstrates how to use the MIDI Studio Core framework
; without any plugins loaded.

[platformio]
default_envs = prod

[env]
framework = arduino
platform = teensy
board = teensy41
monitor_dtr = 0
monitor_rts = 0
board_build.f_cpu = 450000000L
build_flags =
	-D USB_MIDI_SERIAL
	-D TEENSY_OPT_SMALLEST_CODE
	-D LV_CONF_INCLUDE_SIMPLE
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-I src
	-I src/core
	-I src/ui/shared
	-I src/config/ui

extra_scripts =
	pre:script/build/pre_build.py

lib_deps =
	vindar/ILI9341_T4 @ ^1.6.0
	lvgl/lvgl @ ^9.4.0
	luni64/EncoderTool

lib_ignore =
	lvgl_demos
	lvgl_examples

[env:prod]
build_flags =
	${env.build_flags}

[env:debug]
build_flags =
	${env.build_flags}
	-DDEBUG_LOGS
