# Canonical tracked implementation inventory for Core consumers.
# Supported graphs derive their intentional platform exclusions from this list.
set(MS_CORE_PRODUCT_SOURCE_PATHS
    src/context/StandaloneContext.cpp
    src/context/standalone/DeviceSettingsSelectorPresenter.cpp
    src/context/standalone/MacroFeatureModule.cpp
    src/context/standalone/MacroOverlayInvalidationBindings.cpp
    src/context/standalone/MacroOverlayPresenter.cpp
    src/context/standalone/MacroOverlayPresenterActionFormatters.cpp
    src/context/standalone/MacroOverlayPresenterAutomationFormatters.cpp
    src/context/standalone/MacroOverlayPresenterEditFormatters.cpp
    src/context/standalone/MacroOverlayPresenterFormatters.cpp
    src/context/standalone/MacroViewActivationContract.cpp
    src/context/standalone/OverlayPresentationRegistry.cpp
    src/context/standalone/PatternPitchSettingsOverlayPresenter.cpp
    src/context/standalone/ProjectFeatureModule.cpp
    src/context/standalone/ProjectTrackEditorPresenter.cpp
    src/context/standalone/SequencerCcLaneOverlayPresenter.cpp
    src/context/standalone/SequencerChordFieldPresentation.cpp
    src/context/standalone/SequencerChordOverlayFormatters.cpp
    src/context/standalone/SequencerEncoderSyncCoordinator.cpp
    src/context/standalone/SequencerFeatureModule.cpp
    src/context/standalone/SequencerOverlayPresenter.cpp
    src/context/standalone/SequencerOverlayPresenterFormatters.cpp
    src/context/standalone/SequencerOverlayPresenterPresetLibraryFormatters.cpp
    src/context/standalone/SequencerPatternEditorPresenter.cpp
    src/context/standalone/SequencerSettingsOverlayPresenter.cpp
    src/context/standalone/SequencerSettingsOverlayPresenterFormatters.cpp
    src/context/standalone/SettingsFeatureModule.cpp
    src/context/standalone/StandaloneFeatureAssembly.cpp
    src/context/standalone/StandaloneGlobalHandlerAssembly.cpp
    src/context/standalone/StandaloneOverlayAssembly.cpp
    src/context/standalone/StandaloneUiAssembly.cpp
    src/context/standalone/ux/StandaloneGlobalUxSurfaces.cpp
    src/context/standalone/ux/StandaloneMacroUxSurfaces.cpp
    src/context/standalone/ux/StandaloneProjectUxSurfaces.cpp
    src/context/standalone/ux/StandaloneSequencerPresetLibraryUx.cpp
    src/context/standalone/ux/StandaloneSequencerUxSurfaces.cpp
    src/diagnostics/MemoryFootprintReporter.cpp
    src/diagnostics/PerformanceReporter.cpp
    src/diagnostics/StorageQualificationProbe.cpp
    src/handler/common/ModulatorNavigationWorkflow.cpp
    src/handler/common/ProjectRecordedShapeCaptureWorkflow.cpp
    src/handler/common/ProjectRecordedShapeCaptureWorkflowInternals.cpp
    src/handler/common/SharedTrackDomainServices.cpp
    src/handler/macro/MacroAutomationClipboardOps.cpp
    src/handler/macro/MacroAutomationEditorModel.cpp
    src/handler/macro/MacroAutomationHandler.cpp
    src/handler/macro/MacroAutomationPlaybackService.cpp
    src/handler/macro/MacroAutomationTakeInputWorkflow.cpp
    src/handler/macro/MacroAutomationTiming.cpp
    src/handler/macro/MacroDirectTrackStructureTransaction.cpp
    src/handler/macro/MacroEditDomainServices.cpp
    src/handler/macro/MacroEditHandler.cpp
    src/handler/macro/MacroEditModulationServices.cpp
    src/handler/macro/MacroGuardedActionWorkflow.cpp
    src/handler/macro/MacroMidiCcRuntimeAdapter.cpp
    src/handler/macro/MacroMidiHandler.cpp
    src/handler/macro/MacroPerformanceAutomationTakeServices.cpp
    src/handler/macro/MacroPerformanceDomainServices.cpp
    src/handler/macro/MacroPerformanceHandler.cpp
    src/handler/macro/MacroPerformanceModeWorkflow.cpp
    src/handler/macro/MacroStructureAutomationOps.cpp
    src/handler/macro/MacroStructureDomainServices.cpp
    src/handler/macro/MacroStructureWorkflow.cpp
    src/handler/macro/MacroValueHandler.cpp
    src/handler/project/ProjectHandler.cpp
    src/handler/project/ProjectHandlerBindings.cpp
    src/handler/project/ProjectHandlerFocusedEncoderSync.cpp
    src/handler/project/ProjectHandlerInternals.cpp
    src/handler/project/ProjectHandlerKeyboard.cpp
    src/handler/project/ProjectHandlerLifecycle.cpp
    src/handler/project/ProjectHandlerModulatorActions.cpp
    src/handler/project/ProjectHandlerModulatorAudition.cpp
    src/handler/project/ProjectHandlerModulatorValueEditing.cpp
    src/handler/project/ProjectHandlerNavigation.cpp
    src/handler/project/ProjectHandlerValueEditing.cpp
    src/handler/project/ProjectLifecycleDomainServices.cpp
    src/handler/sequencer/PatternPitchSettingsDomainServices.cpp
    src/handler/sequencer/PatternPitchSettingsHandler.cpp
    src/handler/sequencer/ProjectTrackEditorHandler.cpp
    src/handler/sequencer/SequencerCcLaneDomainServices.cpp
    src/handler/sequencer/SequencerCcLaneHandler.cpp
    src/handler/sequencer/SequencerCcLaneLiveProjection.cpp
    src/handler/sequencer/SequencerCcLaneWorkflow.cpp
    src/handler/sequencer/SequencerChordEditOps.cpp
    src/handler/sequencer/SequencerChordFormulaEditOps.cpp
    src/handler/sequencer/SequencerChordPresetDomainServices.cpp
    src/handler/sequencer/SequencerChordPresetLibraryAdapter.cpp
    src/handler/sequencer/SequencerChordProjectionFeedback.cpp
    src/handler/sequencer/SequencerContextSelectorWorkflow.cpp
    src/handler/sequencer/SequencerDirectTrackStructureTransaction.cpp
    src/handler/sequencer/SequencerHistoryDomainServices.cpp
    src/handler/sequencer/SequencerInputUtils.cpp
    src/handler/sequencer/SequencerInteractionPolicyAdapter.cpp
    src/handler/sequencer/SequencerMacroPropertyHandler.cpp
    src/handler/sequencer/SequencerPatternEditorHandler.cpp
    src/handler/sequencer/SequencerPatternQuickControlsHandler.cpp
    src/handler/sequencer/SequencerPreparedPageStructureMutationPlan.cpp
    src/handler/sequencer/SequencerPreparedPageStructureTransaction.cpp
    src/handler/sequencer/SequencerPreparedTrackStructurePlanValidation.cpp
    src/handler/sequencer/SequencerPreparedTrackStructureTransaction.cpp
    src/handler/sequencer/SequencerPresetLibraryHandler.cpp
    src/handler/sequencer/SequencerPresetLibraryPager.cpp
    src/handler/sequencer/SequencerPresetLibraryWorkflow.cpp
    src/handler/sequencer/SequencerPropertySelectorHandler.cpp
    src/handler/sequencer/SequencerStepChordEditorWorkflow.cpp
    src/handler/sequencer/SequencerStepContentActions.cpp
    src/handler/sequencer/SequencerStepContentDraftWorkflow.cpp
    src/handler/sequencer/SequencerStepContentHandler.cpp
    src/handler/sequencer/SequencerStepContextRowWorkflow.cpp
    src/handler/sequencer/SequencerStepEditBindings.cpp
    src/handler/sequencer/SequencerStepEditHandler.cpp
    src/handler/sequencer/SequencerStepEditSessionWorkflow.cpp
    src/handler/sequencer/SequencerStepHandler.cpp
    src/handler/sequencer/SequencerStepPresetDomainServices.cpp
    src/handler/sequencer/SequencerStepPresetLibraryAdapter.cpp
    src/handler/sequencer/SequencerStepValueRowWorkflow.cpp
    src/handler/sequencer/SequencerStructureEditWorkflow.cpp
    src/handler/sequencer/SequencerStructureHistoryUtils.cpp
    src/handler/sequencer/SequencerStructureNavigationWorkflow.cpp
    src/handler/sequencer/SequencerStructurePageClipboardOps.cpp
    src/handler/sequencer/SequencerStructurePageOps.cpp
    src/handler/sequencer/SequencerStructureSelectionOps.cpp
    src/handler/sequencer/SequencerStructureSelectionWorkflow.cpp
    src/handler/sequencer/SequencerStructureStepOps.cpp
    src/handler/sequencer/SequencerStructureStepPasteWorkflow.cpp
    src/handler/sequencer/SequencerStructureTrackOps.cpp
    src/handler/sequencer/SequencerStructureTrackTransferTransaction.cpp
    src/handler/settings/DeviceSettingsDomainServices.cpp
    src/handler/settings/DeviceSettingsHandler.cpp
    src/handler/settings/SequencerSettingsDomainServices.cpp
    src/handler/settings/SequencerSettingsHandler.cpp
    src/handler/transport/TransportHandler.cpp
    src/handler/view/ViewSwitcherHandler.cpp
    src/persistence/AtomicProductFile.cpp
    src/persistence/ChordPresetFileStore.cpp
    src/persistence/DeviceSettingsCodec.cpp
    src/persistence/DeviceSettingsStore.cpp
    src/persistence/MacroTrackBankPersistenceCodec.cpp
    src/persistence/PersistenceChecksum.cpp
    src/persistence/ProductAssetFileStore.cpp
    src/persistence/ProductDirectoryCatalog.cpp
    src/persistence/ProductFileCommitPlan.cpp
    src/persistence/ProductFilePath.cpp
    src/persistence/ProductFileRecoveryPlan.cpp
    src/persistence/ProductFileService.cpp
    src/persistence/ProductFileTransactionJournal.cpp
    src/persistence/ProductFileTransactionJournalCodec.cpp
    src/persistence/ProductPersistenceCoordinator.cpp
    src/persistence/ProductPersistenceJobCoordinator.cpp
    src/persistence/ProductStorageRecoveryService.cpp
    src/persistence/ProductTreeCleanupPlan.cpp
    src/persistence/ProjectControlAutomationPersistence.cpp
    src/persistence/ProjectControlModulationPersistence.cpp
    src/persistence/ProjectControlPersistenceCodec.cpp
    src/persistence/ProjectFileContainer.cpp
    src/persistence/ProjectFileInspection.cpp
    src/persistence/ProjectFileStore.cpp
    src/persistence/ProjectFileTransactions.cpp
    src/persistence/ProjectSaveTransaction.cpp
    src/persistence/ProjectSessionAutosaveService.cpp
    src/persistence/ProjectSessionRestoreService.cpp
    src/persistence/ProjectSessionStore.cpp
    src/persistence/ProjectSnapshotPersistenceCodec.cpp
    src/persistence/ProjectStatePersistenceCodec.cpp
    src/persistence/ProjectTrackStatePersistenceCodec.cpp
    src/persistence/ProjectWorkspacePool.cpp
    src/persistence/SequencerCcLanePersistenceCodec.cpp
    src/persistence/SequencerGraphAssetCodec.cpp
    src/persistence/SequencerGraphRecordCodec.cpp
    src/persistence/SequencerPersistenceCodec.cpp
    src/persistence/SequencerPersistenceEnvelope.cpp
    src/persistence/StepPresetFileStore.cpp
    src/persistence/StorageRecoveryMachine.cpp
    src/protocol/filesystem/FileSystemJobRpc.cpp
    src/protocol/filesystem/FileSystemRpcCodec.cpp
    src/protocol/filesystem/FileSystemRpcConditionalMutation.cpp
    src/protocol/filesystem/FileSystemRpcConditionalPlan.cpp
    src/protocol/filesystem/FileSystemRpcConditionalTransaction.cpp
    src/protocol/filesystem/FileSystemRpcDigest.cpp
    src/protocol/filesystem/FileSystemRpcEndpoint.cpp
    src/protocol/filesystem/FileSystemRpcFileManagement.cpp
    src/protocol/filesystem/FileSystemRpcHandler.cpp
    src/protocol/filesystem/FileSystemRpcInternal.cpp
    src/protocol/filesystem/FileSystemRpcWriteSession.cpp
    src/sequencer/ClockSourceSelector.cpp
    src/sequencer/DrumPlaybackEngine.cpp
    src/sequencer/ExternalClockEstimator.cpp
    src/sequencer/InternalTransportClock.cpp
    src/sequencer/MidiCcGlobalFrameCoordinator.cpp
    src/sequencer/MidiCcGlobalFrameCoordinatorLifecycle.cpp
    src/sequencer/MidiCcGlobalFrameCoordinatorPublication.cpp
    src/sequencer/MidiCcResolutionTelemetryExchange.cpp
    src/sequencer/MidiClockSyncService.cpp
    src/sequencer/ProjectControlClockPublisher.cpp
    src/sequencer/ProjectModulationTriggerQueue.cpp
    src/sequencer/ProjectTrackRuntimeSnapshotBank.cpp
    src/sequencer/RealtimeMidiQueue.cpp
    src/sequencer/SequencerCcLaneRuntime.cpp
    src/sequencer/SequencerInternalTimerLane.cpp
    src/sequencer/SequencerMidiEventSink.cpp
    src/sequencer/SequencerPlaybackService.cpp
    src/sequencer/SequencerRuntimeGraphBank.cpp
    src/sequencer/SequencerRuntimeService.cpp
    src/sequencer/SequencerRuntimeSnapshotBank.cpp
    src/sequencer/SequencerRuntimeStateSync.cpp
    src/sequencer/TemporalMidiCcAuthorSpool.cpp
    src/state/CoreState.cpp
    src/state/CoreStateBootstrap.cpp
    src/state/CoreStateDiagnostics.cpp
    src/state/CoreStateLifecycle.cpp
    src/state/CoreStateProjectHistory.cpp
    src/state/CoreStateSequencerHistoryRecording.cpp
    src/state/CoreStateSequencerHistoryTraversal.cpp
    src/state/CoreStateSharedTracks.cpp
    src/state/MacroEditState.cpp
    src/state/MidiSyncState.cpp
    src/state/SettingsUiState.cpp
    src/state/StateConstructors.cpp
    src/state/StructureClipboardPastePlan.cpp
    src/state/StructureClipboardState.cpp
    src/state/StructureNavigationState.cpp
    src/state/StructureSelectionInteractionPolicy.cpp
    src/state/TrackNavigationState.cpp
    src/state/contextual/GuardedActionState.cpp
    src/state/contextual/OperationFeedbackState.cpp
    src/state/macro/MacroAutomationDomain.cpp
    src/state/macro/MacroAutomationTake.cpp
    src/state/macro/MacroEditMenuModel.cpp
    src/state/macro/MacroHistory.cpp
    src/state/macro/MacroHistoryAssignmentInternals.cpp
    src/state/macro/MacroHistoryAutomationInternals.cpp
    src/state/macro/MacroHistoryCommit.cpp
    src/state/macro/MacroHistoryModulatorAudition.cpp
    src/state/macro/MacroHistoryModulatorCreationInternals.cpp
    src/state/macro/MacroHistoryModulatorDeleteInternals.cpp
    src/state/macro/MacroHistoryModulatorTopology.cpp
    src/state/macro/MacroHistoryRecordedCreationInternals.cpp
    src/state/macro/MacroHistoryRecordedEditInternals.cpp
    src/state/macro/MacroHistoryRecordedShapeCreation.cpp
    src/state/macro/MacroHistoryRecordedShapeEdit.cpp
    src/state/macro/MacroHistoryRedo.cpp
    src/state/macro/MacroHistorySlotEdits.cpp
    src/state/macro/MacroHistorySnapshots.cpp
    src/state/macro/MacroHistoryStructureInternals.cpp
    src/state/macro/MacroHistoryUndo.cpp
    src/state/macro/MacroHistoryValueEdits.cpp
    src/state/macro/MacroInteractionContextBuilder.cpp
    src/state/macro/MacroInteractionPolicy.cpp
    src/state/macro/MacroPagesState.cpp
    src/state/macro/MacroRuntimeState.cpp
    src/state/macro/MacroSlotClipboardPlan.cpp
    src/state/macro/MacroUiState.cpp
    src/state/macro/MacroWorkflow.cpp
    src/state/modulation/ProjectControlMacroConversion.cpp
    src/state/modulation/ProjectControlMacroCurveOps.cpp
    src/state/modulation/ProjectControlMacroOps.cpp
    src/state/modulation/ProjectControlMacroOpsInternal.cpp
    src/state/modulation/ProjectControlRuntime.cpp
    src/state/modulation/ProjectControlRuntimeAdsr.cpp
    src/state/modulation/ProjectControlRuntimeCurve.cpp
    src/state/modulation/ProjectControlRuntimeEvaluation.cpp
    src/state/modulation/ProjectControlState.cpp
    src/state/modulation/ProjectControlStructureTransferOps.cpp
    src/state/modulation/ProjectModulationAutomationOps.cpp
    src/state/modulation/ProjectModulationBindingOps.cpp
    src/state/modulation/ProjectModulationDomainOps.cpp
    src/state/modulation/ProjectModulationDomainQueries.cpp
    src/state/modulation/ProjectModulationDomainValidation.cpp
    src/state/modulation/ProjectModulationRuntimePlan.cpp
    src/state/modulation/ProjectModulatorSourceOps.cpp
    src/state/modulation/ProjectRecordedShapeCaptureState.cpp
    src/state/modulation/ProjectRecordedShapeTake.cpp
    src/state/project/ProjectHistoryCoordinator.cpp
    src/state/project/ProjectMenuModel.cpp
    src/state/project/ProjectMenuNavigation.cpp
    src/state/project/ProjectModulatorMenuModel.cpp
    src/state/project/ProjectNameKeyboard.cpp
    src/state/project/ProjectNavigationState.cpp
    src/state/project/ProjectSettingsHistory.cpp
    src/state/project/ProjectSlug.cpp
    src/state/project/ProjectSnapshot.cpp
    src/state/project/ProjectSnapshotLifecycle.cpp
    src/state/project/ProjectState.cpp
    src/state/project/ProjectTrackDomainOps.cpp
    src/state/project/ProjectTrackDomainServices.cpp
    src/state/project/ProjectTrackEditorOps.cpp
    src/state/project/ProjectTrackEditorState.cpp
    src/state/project/ProjectTrackHistory.cpp
    src/state/project/ProjectTrackState.cpp
    src/state/sequencer/DrumPatternState.cpp
    src/state/sequencer/SequencerCcLaneDomain.cpp
    src/state/sequencer/SequencerCcLanePatternOps.cpp
    src/state/sequencer/SequencerCcLaneProjectionOps.cpp
    src/state/sequencer/SequencerCcLaneRouting.cpp
    src/state/sequencer/SequencerChordContextProjection.cpp
    src/state/sequencer/SequencerChordPresetModel.cpp
    src/state/sequencer/SequencerChordProjectionWorkspace.cpp
    src/state/sequencer/SequencerChordUiOps.cpp
    src/state/sequencer/SequencerContentProjectionOps.cpp
    src/state/sequencer/SequencerContentStepOps.cpp
    src/state/sequencer/SequencerContentViewInternal.cpp
    src/state/sequencer/SequencerContentViewOps.cpp
    src/state/sequencer/SequencerExpansionBudgetProjection.cpp
    src/state/sequencer/SequencerGraphAsset.cpp
    src/state/sequencer/SequencerGraphCanonicalPolicy.cpp
    src/state/sequencer/SequencerGraphChildOps.cpp
    src/state/sequencer/SequencerGraphContentOps.cpp
    src/state/sequencer/SequencerGraphOps.cpp
    src/state/sequencer/SequencerGraphPropertyOps.cpp
    src/state/sequencer/SequencerHistory.cpp
    src/state/sequencer/SequencerInteractionContextOps.cpp
    src/state/sequencer/SequencerInteractionPolicy.cpp
    src/state/sequencer/SequencerNoteSpelling.cpp
    src/state/sequencer/SequencerPatternEditorOps.cpp
    src/state/sequencer/SequencerPatternEditorState.cpp
    src/state/sequencer/SequencerPatternRandomizeOps.cpp
    src/state/sequencer/SequencerPatternRandomizeSession.cpp
    src/state/sequencer/SequencerPatternRegionOps.cpp
    src/state/sequencer/SequencerPitchEditAuthority.cpp
    src/state/sequencer/SequencerProjectScaleOps.cpp
    src/state/sequencer/SequencerQuickControlsDraft.cpp
    src/state/sequencer/SequencerResolvedDisplayProjectionOps.cpp
    src/state/sequencer/SequencerSnapshotOps.cpp
    src/state/sequencer/SequencerState.cpp
    src/state/sequencer/SequencerStepContentDraftOps.cpp
    src/state/sequencer/SequencerStepContentDraftSession.cpp
    src/state/sequencer/SequencerStepPastePlan.cpp
    src/state/sequencer/SequencerStepPresetModel.cpp
    src/state/sequencer/SequencerStructureHistory.cpp
    src/state/sequencer/SequencerTrackActivationQueue.cpp
    src/state/sequencer/SequencerTrackBankOps.cpp
    src/state/sequencer/SequencerTrackBankState.cpp
    src/state/sequencer/SequencerTrackTransferAction.cpp
    src/state/sequencer/SequencerUiState.cpp
    src/state/settings/DeviceSettingsMenuModel.cpp
    src/state/shared/MidiCcDestinationResolver.cpp
    src/state/shared/SharedTrackCoordinator.cpp
    src/state/shared/StructureSlotOps.cpp
    src/ui/common/AddSlotIcon.cpp
    src/ui/common/CoalescedLvglRenderScheduler.cpp
    src/ui/common/GlobalTrackNavigationStripModel.cpp
    src/ui/common/TrackHeaderRow.cpp
    src/ui/common/TrackNavigationStrip.cpp
    src/ui/font/StandaloneFonts.cpp
    src/ui/macro/MacroEditorOverlay.cpp
    src/ui/macro/MacroEditorPreviewModel.cpp
    src/ui/macro/MacroHeaderBar.cpp
    src/ui/modulation/ModulatorAdsrUiModel.cpp
    src/ui/modulation/ModulatorSparklineModel.cpp
    src/ui/project/ProjectModulatorUiModel.cpp
    src/ui/project/ProjectModulatorWorkspace.cpp
    src/ui/project/ProjectNameKeyboardView.cpp
    src/ui/project/ProjectTrackEditorOverlay.cpp
    src/ui/project/ProjectTrackEditorViewModel.cpp
    src/ui/sequencer/SequencerBottomActionStripViewModelBuilder.cpp
    src/ui/sequencer/SequencerCcLaneGrid.cpp
    src/ui/sequencer/SequencerCcLaneGridViewModelBuilder.cpp
    src/ui/sequencer/SequencerChordPresetPresentation.cpp
    src/ui/sequencer/SequencerChordVoiceRail.cpp
    src/ui/sequencer/SequencerHeaderBar.cpp
    src/ui/sequencer/SequencerHeaderBarRenderModel.cpp
    src/ui/sequencer/SequencerHeaderViewModelBuilder.cpp
    src/ui/sequencer/SequencerLeftActionStripViewModelBuilder.cpp
    src/ui/sequencer/SequencerPatternEditorOverlay.cpp
    src/ui/sequencer/SequencerPatternTimelineModel.cpp
    src/ui/sequencer/SequencerPresetLibraryPresentation.cpp
    src/ui/sequencer/SequencerPropertyOverlayViewModelBuilder.cpp
    src/ui/sequencer/SequencerQuickControlVisuals.cpp
    src/ui/sequencer/SequencerStepContentDraftTransitionLabels.cpp
    src/ui/sequencer/SequencerStepEditOverlay.cpp
    src/ui/sequencer/SequencerStepGridViewModelBuilder.cpp
    src/ui/sequencer/SequencerTrackPastePendingViewModel.cpp
    src/ui/sequencer/SequencerTrackPastePreflightCard.cpp
    src/ui/sequencer/SequencerTrackPastePreflightViewModel.cpp
    src/ui/sequencer/SequencerTrackPasteProjection.cpp
    src/ui/sequencer/SequencerViewModelBuilder.cpp
    src/ui/sequencer/StepContentBadgeProjection.cpp
    src/ui/sequencer/StepGrid.cpp
    src/ui/sequencer/StepGridFrameLogic.cpp
    src/ui/sequencer/StepGridGeometryLogic.cpp
    src/ui/sequencer/StepGridLabelLogic.cpp
    src/ui/sequencer/StepGridLabelRenderer.cpp
    src/ui/sequencer/StepGridRenderLogic.cpp
    src/ui/sequencer/StepGridRenderPlanner.cpp
    src/ui/sequencer/StepGridWidgets.cpp
    src/ui/sequencer/StepPropertySelectionOverlay.cpp
    src/ui/sequencer/StepPropertyVisuals.cpp
    src/ui/strip/ContextActionStrip.cpp
    src/ui/transportbar/ContextSoftkeyBar.cpp
    src/ui/transportbar/TransportBar.cpp
    src/ui/view/DeviceSettingsView.cpp
    src/ui/view/MacroView.cpp
    src/ui/view/MacroViewModelBuilder.cpp
    src/ui/view/MainViewFrame.cpp
    src/ui/view/ProjectView.cpp
    src/ui/view/ProjectViewModulators.cpp
    src/ui/view/RetainedViewRenderPolicy.cpp
    src/ui/view/SequencerView.cpp
    src/ui/widget/MacroKnobWidget.cpp
    src/validation/project/ProjectModulationBenchmark.cpp
    src/validation/project/ProjectStoreSmoke.cpp
    src/validation/ux/SemanticUxContext.cpp
    src/validation/ux/SemanticUxNames.cpp
    src/validation/ux/SemanticUxRecorder.cpp
    src/validation/ux/SemanticUxSurface.cpp
    src/validation/ux/SequencerTrackTransferSemanticProjection.cpp
)

set(MS_CORE_PRODUCT_SOURCES ${MS_CORE_PRODUCT_SOURCE_PATHS})
list(TRANSFORM MS_CORE_PRODUCT_SOURCES
    PREPEND "${CMAKE_CURRENT_LIST_DIR}/../")
